
import React from 'react';
import { AtsAnalysis } from '../types';
import { CheckCircle2, AlertCircle, XCircle, Info, Lightbulb } from 'lucide-react';

interface AtsFeedbackDetailsProps {
  analysis: AtsAnalysis | null;
  loading: boolean;
}

const AtsFeedbackDetails: React.FC<AtsFeedbackDetailsProps> = ({ analysis, loading }) => {
  if (!analysis && !loading) return null;

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'good': return <CheckCircle2 className="text-green-500" size={20} />;
      case 'warning': return <AlertCircle className="text-amber-500" size={20} />;
      case 'critical': return <XCircle className="text-red-500" size={20} />;
      default: return <Info className="text-slate-400" size={20} />;
    }
  };

  const getStatusClass = (status: string) => {
    switch (status) {
      case 'good': return 'border-green-100 bg-green-50/30';
      case 'warning': return 'border-amber-100 bg-amber-50/30';
      case 'critical': return 'border-red-100 bg-red-50/30';
      default: return 'border-slate-100 bg-slate-50/30';
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-lg border border-slate-200 overflow-hidden animate-in fade-in slide-in-from-top-4 duration-500">
      <div className="bg-slate-900 px-6 py-4 flex items-center justify-between">
        <h3 className="text-white font-bold flex items-center gap-2">
          <Lightbulb size={18} className="text-amber-400" />
          Detailed ATS Optimization Report
        </h3>
        {analysis && (
          <span className="text-xs font-bold text-slate-400 uppercase tracking-widest">
            Score: {analysis.score}/100
          </span>
        )}
      </div>

      <div className="p-6">
        {loading ? (
          <div className="space-y-4">
            <div className="h-4 bg-slate-100 rounded w-1/4 animate-pulse" />
            <div className="space-y-3">
              {[1, 2, 3].map(i => (
                <div key={i} className="h-20 bg-slate-50 rounded-lg animate-pulse" />
              ))}
            </div>
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-4">
            {analysis?.feedbacks.length === 0 ? (
              <p className="text-center text-slate-500 py-8 italic">No detailed feedback available yet. Run analysis to see results.</p>
            ) : (
              analysis?.feedbacks.map((item, idx) => (
                <div key={idx} className={`p-4 rounded-xl border transition-all hover:shadow-md ${getStatusClass(item.status)}`}>
                  <div className="flex gap-4">
                    <div className="shrink-0 mt-1">{getStatusIcon(item.status)}</div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">{item.category}</span>
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase ${
                          item.status === 'good' ? 'bg-green-100 text-green-700' : 
                          item.status === 'warning' ? 'bg-amber-100 text-amber-700' : 
                          'bg-red-100 text-red-700'
                        }`}>
                          {item.status}
                        </span>
                      </div>
                      <h4 className="text-sm font-bold text-slate-800 mb-1">{item.message}</h4>
                      {item.suggestion && (
                        <div className="mt-2 text-xs text-slate-600 bg-white/50 p-2 rounded-lg border border-slate-100 flex gap-2">
                          <span className="font-bold text-indigo-600 shrink-0">Suggestion:</span>
                          <span>{item.suggestion}</span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        )}
      </div>
      
      <div className="bg-slate-50 px-6 py-3 border-t flex justify-between items-center text-[10px] text-slate-400 font-bold uppercase tracking-wider">
        <span>Generated by CareerPro AI Analysis</span>
        <span>{new Date().toLocaleDateString()}</span>
      </div>
    </div>
  );
};

export default AtsFeedbackDetails;
